# This Dockerfile can be used to confirm that setup_oracle_client runs
# correctly on different shells.  Build the container from the project root
# with the following
#
#   docker build -t test-shells -f test/Dockerfile.test_shells .
#
# The build will fail if setup_oracle_client uses incompatible syntax
FROM python:3.8-slim

# Install package dependencies
RUN apt-get update -y && \
    apt-get install -y \
        zsh

# Install Python modules
ENV APP=/app
ENV PYTHONPATH=$APP
WORKDIR $APP
RUN mkdir etlhelper

# Install cx_Oracle (required to run setup tool
RUN pip install cx_Oracle

# Copy app files to container
COPY setup.py versioneer.py setup.cfg README.md $APP/
COPY etlhelper/ $APP/etlhelper

# Install etlhelper and setup_oracle_client tool
RUN python -m pip install .
RUN setup_oracle_client -v
ENV LD_LIBRARY_PATH=/some/demo/path

# Run library_prepend with different shells to confirm no errors
RUN /bin/bash /app/etlhelper/oracle_instantclient/ld_library_prepend.sh
RUN /bin/sh /app/etlhelper/oracle_instantclient/ld_library_prepend.sh
RUN /bin/zsh /app/etlhelper/oracle_instantclient/ld_library_prepend.sh
