language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'

install:
  - sudo apt-get update
  - sudo apt-get install build-essential curl apt-transport-https unixodbc-dev
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install .

script: 
  - flake8 etlhelper test
  - pytest -vvs -rst test/unit

