name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: 
      - main
    paths:
      - 'docs/**'  
      - 'etlhelper/**'
      - '.github/**'

jobs:
  pages:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Install RTD Theme
      run: |
          pip install sphinx sphinx_rtd_theme
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        python-version: '3.10'
